### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by tteuer** [nicoduj/homebridge-deebotEcovacs#19]
Hello, 

I am trying to install this Homebridge plug in and and unable. I get numerous errors. Other plugins are running/updating/installing without issue. I am installing it through Homebridge Config UI.

CMD: npm install homebridge-deebotecovacs@latest

npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js

> canvas@2.6.1 install /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-darwin-unknown-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.1.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to 'pkg-config cairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas
gyp ERR! node -v v14.1.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/14.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 19.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/14.1.0/bin/node" "/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas
node-pre-gyp ERR! node -v v14.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/14.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-05-04T16_55_37_741Z-debug.log

**Comment by nicoduj** [comment]
Hi, did you read the README / INSTALL WARNING in config UI before installing ? Your problem is related to canvas which needs to be compiled on your environment and thus needs some prerequisite.

Full text from README : 

**IMPORTANT**
If you encounter any issue while installing, you might have to install additionnal packages on your environment since the main dependency of it depends on canvas library which is not available for all configurations. See there for more details : [canvas compiling](https://github.com/Automattic/node-canvas#compiling).

For use in the [oznu/homebridge](https://github.com/oznu/docker-homebridge) Docker image (Alpine Linux) please add the following line to your `startup.sh` script and restart the container. You can edit this file in directly in the Homebride UI by selecting the drop down menu in the upper-right-corner and selecting _Startup Script_.

```
apk add build-base cairo-dev jpeg-dev pango-dev giflib-dev librsvg-dev
```

You can also use the [PACKAGES](https://github.com/oznu/docker-homebridge#optional-settings) env variable directly with docker

```bash
-e PACKAGES=build-base,cairo-dev,jpeg-dev,pango-dev,giflib-dev,librsvg-dev
```

**Comment by tteuer** [comment]
Hi Nicoduj,

Thanks for the quick response and my apologies for missing that part about canvas. I'd assumed that npm would have handled all of the dependencies properly. 

I was able to get canvas and it's dependencies compiled/installed. The Ecobot plugin installed and prompted me to enter in my Ecovac account information. Homebridge will not restart now, however. Taking a look at the logs, it appears the Ecovac plugin is causing an error and sending a SIGTERM to Homebridge. 

[5/4/2020, 10:24:59 AM] TypeError: domain.enter is not a function
    at EcovacsMQTT.EventEmitter.emit (domain.js:546:10)
    at /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:73:33
    at cb (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:634:7)
    at MqttClient._handleAck (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:1249:7)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:358:12)
    at work (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:334:11)
TypeError: domain.enter is not a function
    at EcovacsMQTT.EventEmitter.emit (domain.js:546:10)
    at /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:73:33
    at cb (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:634:7)
    at MqttClient._handleAck (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:1249:7)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:358:12)
    at work (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:334:11)
[5/4/2020, 10:24:59 am] [SmartThings-v2] ERROR: uncaughtException: domain.enter is not a function
TypeError: domain.enter is not a function
    at EcovacsMQTT.EventEmitter.emit (domain.js:546:10)
    at /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:73:33
    at cb (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:634:7)
    at MqttClient._handleAck (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:1249:7)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:358:12)
    at work (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/readable-stream/lib/_stream_writable.js:334:11) 
[5/4/2020, 10:24:59 am] [SmartThings-v2] INFO: INFO: Your plugin version is up-to-date 
[5/4/2020, 10:24:59 am] [SmartThings-v2] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.3 
[5/4/2020, 10:24:59 AM] Got SIGTERM, shutting down Homebridge...
[5/4/2020, 10:24:59 AM] [DeebotEcovacs] INFO - shutdown

**Comment by nicoduj** [comment]
Hi, it is strange another plugin is sending the same error :

[5/4/2020, 10:24:59 am] [SmartThings-v2] ERROR: uncaughtException: domain.enter is not a function

Could you share your config and do a npm list to see version of packages ?

What is your deebot model also ?

**Comment by tteuer** [comment]
I noticed that too with the SmartThings-v2 error. When I remove the Ecovacs plugin from my config.json, Homebridge launches normally and there are no errors from SmartThings-v2, including the one quoted above. 

I have a **Deebot 901**

**My config, with Ecovacs added (with some user names/IDs removed):**
{
    "bridge": {
        "name": "Homebridge",
        "username": "removed",
        "pin": "removed"
    },
    "description": "Homebridge",
    "platforms": [
        {
            "name": "Config",
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "log": {
                "method": "file",
                "path": "~/.homebridge/logfile.log"
            },
            "accessoryControl": {
                "debug": true
            },
            "platform": "config"
        },
        {
            "name": "SmartThings-v2",
            "local_commands": true,
            "temperature_unit": "F",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": false,
                "hideNamePrefix": false,
                "file": {
                    "enabled": true,
                    "level": "good"
                }
            },
            "platform": "SmartThings-v2"
        },
        {
            "email": "removed",
            "password": "removed",
            "countryCode": "US",
            "refreshTimer": 0,
            "platform": "DeebotEcovacs"
        }
    ],
    "accessories": [
        {
            "accessory": "Chamberlain",
            "name": "Garage Door",
        },
        {
            "accessory": "DummySwitch",
            "name": "August Lock Trigger",
            "stateful": true
        },
        {
            "accessory": "DummySwitch",
            "name": "Garage Door Trigger",
            "stateful": true
        },
        {
            "name": "Living Room TV",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "infoButtonAction": "INFO",
            "accessory": "webostv"
        }
    ]
}

**npm list**
└─┬ canvas@2.6.1
  ├── nan@2.14.1
  ├─┬ node-pre-gyp@0.11.0
  │ ├── detect-libc@1.0.3
  │ ├─┬ mkdirp@0.5.5
  │ │ └── minimist@1.2.5
  │ ├─┬ needle@2.4.1
  │ │ ├─┬ debug@3.2.6
  │ │ │ └── ms@2.1.2
  │ │ ├─┬ iconv-lite@0.4.24
  │ │ │ └── safer-buffer@2.1.2
  │ │ └── sax@1.2.4
  │ ├─┬ nopt@4.0.3
  │ │ ├── abbrev@1.1.1
  │ │ └─┬ osenv@0.1.5
  │ │   ├── os-homedir@1.0.2
  │ │   └── os-tmpdir@1.0.2
  │ ├─┬ npm-packlist@1.4.8
  │ │ ├─┬ ignore-walk@3.0.3
  │ │ │ └─┬ minimatch@3.0.4
  │ │ │   └─┬ brace-expansion@1.1.11
  │ │ │     ├── balanced-match@1.0.0
  │ │ │     └── concat-map@0.0.1
  │ │ ├─┬ npm-bundled@1.1.1
  │ │ │ └── npm-normalize-package-bin@1.0.1 deduped
  │ │ └── npm-normalize-package-bin@1.0.1
  │ ├─┬ npmlog@4.1.2
  │ │ ├─┬ are-we-there-yet@1.1.5
  │ │ │ ├── delegates@1.0.0
  │ │ │ └─┬ readable-stream@2.3.7
  │ │ │   ├── core-util-is@1.0.2
  │ │ │   ├── inherits@2.0.4 deduped
  │ │ │   ├── isarray@1.0.0
  │ │ │   ├── process-nextick-args@2.0.1
  │ │ │   ├── safe-buffer@5.1.2 deduped
  │ │ │   ├─┬ string_decoder@1.1.1
  │ │ │   │ └── safe-buffer@5.1.2 deduped
  │ │ │   └── util-deprecate@1.0.2
  │ │ ├── console-control-strings@1.1.0
  │ │ ├─┬ gauge@2.7.4
  │ │ │ ├── aproba@1.2.0
  │ │ │ ├── console-control-strings@1.1.0 deduped
  │ │ │ ├── has-unicode@2.0.1
  │ │ │ ├── object-assign@4.1.1
  │ │ │ ├── signal-exit@3.0.3
  │ │ │ ├─┬ string-width@1.0.2
  │ │ │ │ ├── code-point-at@1.1.0
  │ │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │ │ │ └── number-is-nan@1.0.1
  │ │ │ │ └── strip-ansi@3.0.1 deduped
  │ │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ │ └── ansi-regex@2.1.1
  │ │ │ └─┬ wide-align@1.1.3
  │ │ │   └── string-width@1.0.2 deduped
  │ │ └── set-blocking@2.0.0
  │ ├─┬ rc@1.2.8
  │ │ ├── deep-extend@0.6.0
  │ │ ├── ini@1.3.5
  │ │ ├── minimist@1.2.5 deduped
  │ │ └── strip-json-comments@2.0.1
  │ ├─┬ rimraf@2.7.1
  │ │ └─┬ glob@7.1.6
  │ │   ├── fs.realpath@1.0.0
  │ │   ├─┬ inflight@1.0.6
  │ │   │ ├── once@1.4.0 deduped
  │ │   │ └── wrappy@1.0.2 deduped
  │ │   ├── inherits@2.0.4
  │ │   ├── minimatch@3.0.4 deduped
  │ │   ├── once@1.4.0 deduped
  │ │   └── path-is-absolute@1.0.1
  │ ├── semver@5.7.1
  │ └─┬ tar@4.4.13
  │   ├── chownr@1.1.4
  │   ├─┬ fs-minipass@1.2.7
  │   │ └── minipass@2.9.0 deduped
  │   ├─┬ minipass@2.9.0
  │   │ ├── safe-buffer@5.1.2 deduped
  │   │ └── yallist@3.1.1 deduped
  │   ├─┬ minizlib@1.3.3
  │   │ └── minipass@2.9.0 deduped
  │   ├── mkdirp@0.5.5 deduped
  │   ├── safe-buffer@5.1.2
  │   └── yallist@3.1.1
  └─┬ simple-get@3.1.0
    ├─┬ decompress-response@4.2.1
    │ └── mimic-response@2.1.0
    ├─┬ once@1.4.0
    │ └── wrappy@1.0.2
    └── simple-concat@1.0.0

**Comment by nicoduj** [comment]
I think there is some conflict there,would you mind trying without SmartThings-v2 ?

**Comment by nicoduj** [comment]
I have made a pull request to a dep since I think there is something that could lead to such issue, however not sur. Could you tell me your node version also ?

**Comment by tteuer** [comment]
I will try disabling the SmartThings Plugin later today, but Node is version 14.1.0

**Comment by nicoduj** [comment]
ok, let me know. If you want you can also try to do the modification in your dependenceis I made on the pull request mentioned.

**Comment by tteuer** [comment]
Good news, I merged the change of the ecovacs-deebot.js dependency you'd mentioned and it WORKED! I didn't have to disable SmartThings at all. Thank you again for your help and all of your hardworking!
