### ISSUE TITLE
The plugin forces a restart after a crash

### ISSUE THREAD

**Issue by Bastie82** [nicoduj/homebridge-deebotEcovacs#47]
Unfortunately the plugin crashes and forces a restart?

```
[26/12/2020, 12:03:08] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Error: read ECONNRESET')
    at EcovacsMQTT_JSON.emit (events.js:304:17)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:48:25)
    at MqttClient.emit (events.js:327:22)
    at TLSSocket.streamErrorHandler (/usr/local/lib/node_modules/homebridge-deebot/node_modules/mqtt/lib/client.js:343:12)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

```
[26/12/2020, 12:07:25] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Error: connect ECONNREFUSED 47.254.143.26:8883')
    at EcovacsMQTT_JSON.emit (events.js:304:17)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:48:25)
    at MqttClient.emit (events.js:327:22)
    at TLSSocket.streamErrorHandler (/usr/local/lib/node_modules/homebridge-deebot/node_modules/mqtt/lib/client.js:343:12)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[26/12/2020, 12:07:25] Got SIGTERM, shutting down Homebridge...
[26/12/2020, 12:07:26] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Error: connect ECONNREFUSED 47.254.143.26:8883')
    at EcovacsMQTT_JSON.emit (events.js:304:17)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:48:25)
    at MqttClient.emit (events.js:327:22)
    at TLSSocket.streamErrorHandler (/usr/local/lib/node_modules/homebridge-deebot/node_modules/mqtt/lib/client.js:343:12)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by mrbungle64** [comment]
@Bastie82 

The Ecovacs servers are currently not reachable

**Comment by nicoduj** [comment]
Hi, I had some issues this week end also, will try to better handle errors like this if I can, because from the log I see that it crash in the lib. Any though @mrbungle64  ?

**Comment by maxymkov** [comment]
Hi, I'm getting plugin crashed upon launch, and HB restart. But log looks different:
TypeError: Cannot read properties of undefined (reading 'continent')
    at new DeebotEcovacsAPI (/usr/local/lib/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js:22:48)
    at new myDeebotEcovacsPlatform (/usr/local/lib/node_modules/homebridge-deebotecovacs/index.js:67:27)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:442:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:161:29)
Unfortunately, I have no skills to understand what is wrong and how to fix.

**Comment by mrbungle64** [comment]
@maxymkov 

Have you already checked if you're using a valid country code?
https://github.com/nicoduj/homebridge-deebotEcovacs#homebridge-configuration

**Comment by maxymkov** [comment]
> @maxymkov
> 
> Have you already checked if you're using a valid country code? https://github.com/nicoduj/homebridge-deebotEcovacs#homebridge-configuration

Thanks for feedback,
My country code is "OTHER", and for sure it is.
