### ISSUE TITLE
TypeError: vacBot.hasSpotAreas is not a function

### ISSUE THREAD

**Issue by zacechola** [nicoduj/homebridge-deebotEcovacs#75]
Fresh install on a new Raspberry Pi 4, I'm running into this TypeError. I have uninstalled and reinstalled the plugin a few times but only keep getting the same error.

**OS** Raspbian GNU/Linux Buster (10)
**Node version** v14.17.4
**npm version** v7.20.3

```
[31/08/2021, 08:02:47] [DeebotEcovacs] INFO - Discovered Deebot : E2000741291902923485
[31/08/2021, 08:02:47] [DeebotEcovacs] INFO - Edge Cleaning for E2000741291902923485 : true
[31/08/2021, 08:02:47] [DeebotEcovacs] INFO - Spot Cleaning for E2000741291902923485 : true
[31/08/2021, 08:02:47] [DeebotEcovacs] INFO - SpotArea Cleaning for E2000741291902923485 : false
[31/08/2021, 08:02:47] [DeebotEcovacs] INFO - CustomArea Cleaning for E2000741291902923485 : false
[31/08/2021, 08:02:53] TypeError: vacBot.hasSpotAreas is not a function
    at EcovacsXMPP.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js:86:18)
    at EcovacsXMPP.emit (events.js:412:35)
    at EcovacsXMPP.session_start (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/ecovacs-deebot/library/ecovacs.js:29:14)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/ecovacs-deebot/library/ecovacsXMPP.js:17:18)
    at EventEmitter.emit (events.js:400:28)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/simple-xmpp/lib/simple-xmpp.js:311:20)
    at Client.emit (events.js:400:28)
    at Client.useFeatures (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/node-xmpp-client/lib/Client.js:365:10)
    at Client._handleSessionState (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/node-xmpp-client/lib/Client.js:261:10)
    at Client._handleStanza (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/node-xmpp-client/lib/Client.js:242:14)
[31/08/2021, 08:02:53] Got SIGTERM, shutting down Homebridge...
[31/08/2021, 08:02:54] [DeebotEcovacs] INFO - shutdown
```

Ends up getting caught in a loop that causes the Homebridge to restart over and over with every SIGTERM.

**Comment by mrbungle64** [comment]
@zacechola 

Please install the plugin again. It should work now.
I published a new version of the underlying library where I fixed a backward compatibility issue that effected this plugin.

@nicoduj 
I already created a [pull request](https://github.com/nicoduj/homebridge-deebotEcovacs/pull/74) for your plugin to ensure compatibility.

**Comment by zacechola** [comment]
That worked!
