### ISSUE TITLE
Error causing reboot loop

### ISSUE THREAD

**Issue by damanveen** [nicoduj/homebridge-deebotEcovacs#76]
Getting the following error:

[01/09/2021, 14:01:01] [DeebotEcovacs] INFO - stopping deebots discovery, number of deebots found : 1
[01/09/2021, 14:01:01] [DeebotEcovacs] INFO - Discovered Deebot : Shamu
[01/09/2021, 14:01:01] [DeebotEcovacs] INFO - Edge Cleaning for Shamu : true
[01/09/2021, 14:01:01] [DeebotEcovacs] INFO - Spot Cleaning for Shamu : true
[01/09/2021, 14:01:01] [DeebotEcovacs] INFO - SpotArea Cleaning for Shamu : false
[01/09/2021, 14:01:01] [DeebotEcovacs] INFO - CustomArea Cleaning for Shamu : false
[01/09/2021, 14:01:06] TypeError: vacBot.hasSpotAreas is not a function
    at EcovacsMQTT_JSON.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js:86:18)
    at EcovacsMQTT_JSON.emit (events.js:412:35)
    at /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:36:33
    at cb (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:705:7)
    at MqttClient._handleAck (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:1367:7)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:417:12)
    at work (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
[01/09/2021, 14:01:06] Got SIGTERM, shutting down Homebridge...
[01/09/2021, 14:01:06] [DeebotEcovacs] INFO - shutdown
[01/09/2021, 14:01:11] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[01/09/2021, 14:01:16] [HB Supervisor] Restarting Homebridge...

**Comment by mrbungle64** [comment]
@damanveen 

Please reinstall the plugin. Should fix the problem.
