### ISSUE TITLE
Allow manual naming override of SpotArea and CustomArea switch

### ISSUE THREAD

**Issue by dresken** [nicoduj/homebridge-deebotEcovacs#83]
Feature Request: Instead of the automatic labelling (eg "SpotArea 4 Deebot") allow a name to be specified for a switch. 

As I rename these in Home afterward to something more useful, but then I lose what number is actually what switch if they need any updates.

Cheers

**Comment by nicoduj** [comment]
Hi,

I did not implement this since most users are relying on home feature to rename switches, and moreover I can't prevent that. I understand however what you mean, so I am putting this in the backlog.

**Comment by nicoduj** [comment]
1.4.8-beta.1 , but could not test it since I have no deebot with spot / custom area feature.

**Comment by dresken** [comment]
Thank you so much.

Just nothing for others that it didn't like adding a name to existing config and showed the below error - I've removed the cached accessory and it now seems fine.

Error: Cannot add a Service with the same UUID 'XXXXXXXX-XXXX-XXXX-XXXXX-XXXXXXXXXXX' and subtype 'SwitchSpotAreaService0Deebot' as another Service in this Accessory.
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:473:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at myDeebotEcovacsPlatform.loadDeebots (/usr/local/lib/node_modules/homebridge-deebotecovacs/index.js:500:27)
    at DeebotEcovacsAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/index.js:193:31)
    at DeebotEcovacsAPI.emit (node:events:390:28)
    at /usr/local/lib/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js:62:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
